name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo for demo
          uses: actions/checkout@v4
          with:
            path: main
        - name: welcome message
          run: echo "My First Github actions demo"