name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo for demo
          uses: actions/checkout@v4
        - name: list and read file
          run: |
            echo "List and Read github repo files"
            ls -ltra
            cat README.md
        
        - name: Generate ASCII code
          run: cowsay -f duck "Run for cover, I am duck quacckkk... QUACKKKK" >> duck.txt

